Considering the Breast Cancer Wisconsin dataset, we carry out the following tasks:

- Load the dataset from sklearn

In [1]:
from sklearn import datasets

In [2]:
dataset = datasets.load_breast_cancer()

In [3]:
print(dataset.data)   # data values

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]

In [4]:
print(dataset.feature_names)   # names of our input features

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

In [5]:
print(dataset.target_names)   # names of our target classes

['malignant' 'benign']

In [6]:
print(dataset.target)        # 0: malignant; 1: benign

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1]

In [7]:
# Let us create a dataframe out of this dataset

import pandas as pd

In [8]:
ip_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)

In [9]:
ip_df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [10]:
ip_df["Cancer"] = dataset.target

In [11]:
ip_df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Cancer
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

- Find the number of classes in the dataset

In [12]:
print(f'The number of classes in the dataset is {ip_df["Cancer"].nunique()}')

The number of classes in the dataset is 2

In [13]:
print(f'The names of the classes in the dataset are {dataset.target_names[0]} and {dataset.target_names[1]}')

The names of the classes in the dataset are malignant and benign

In [14]:
ip_df['Cancer'].value_counts()

Cancer
1    357
0    212
Name: count, dtype: int64

# *The dataset is fairly imbalanced.*

- Stratified K-fold cross validation seems to be a better approach after choosing an appropriate value of K

In [15]:
# The number of folds, K, is a hyperparameter and the appropriate way of choosing it
# is by applying hyperparameter tuning. Here, we are randomly selecting K=5.

K = 5

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X, y = ip_df.iloc[:, :-1].values, ip_df.iloc[:, -1].values

In [18]:
print(f'X type is {type(X)}, y type is {type(y)}')

X type is <class 'numpy.ndarray'>, y type is <class 'numpy.ndarray'>

In [19]:
X.shape

(569, 30)

In [20]:
# It is time to set aside the test set and work only with X_train and y_train

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
X_train.shape, y_train.shape

((455, 30), (455,))

In [22]:
from sklearn.model_selection import KFold

In [23]:
kf = KFold(n_splits=K)   # creating an instance of the KFold class

In [24]:
def get_score(model, X_train, X_val, y_train, y_val):
    model.fit(X_train, y_train)
    return model.score(X_val, y_val)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np

In [26]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, val_index in kf.split(X_train, y_train):
    X_train_new, X_val, y_train_new, y_val = X_train[train_index], X_train[val_index], y_train[train_index], y_train[val_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear'), X_train_new, X_val, y_train_new, y_val))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train_new, X_val, y_train_new, y_val))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train_new, X_val, y_train_new, y_val))

In [27]:
print(scores_logistic)
print(scores_svm)
print(scores_rf)

[0.967032967032967, 0.945054945054945, 0.9560439560439561, 0.945054945054945, 0.9230769230769231]
[0.6703296703296703, 0.6923076923076923, 0.6043956043956044, 0.5384615384615384, 0.6373626373626373]
[0.989010989010989, 0.967032967032967, 0.967032967032967, 0.945054945054945, 0.9560439560439561]

In [28]:
print(f"Logistic performance: {np.mean(scores_logistic)}")
print(f"SVM performance: {np.mean(scores_svm)}")
print(f"Random forest performance: {np.mean(scores_rf)}")

Logistic performance: 0.9472527472527472
SVM performance: 0.6285714285714286
Random forest performance: 0.964835164835165

In [29]:
best_model = RandomForestClassifier(n_estimators=40)

In [30]:
best_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=40)

In [31]:
best_model.score(X_test, y_test)

0.9649122807017544